name: CI
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: TopoToolbox/actions/checkout@main
        with:
          submodules: true
      - name: Install dependencies on macos
        if: matrix.os == 'macos-latest'
        run: brew install gdal proj
      - name: Set PROJ_DATA
        if: matrix.os == 'macos-latest'
        run: |
          echo "PROJ_DATA=$(brew --prefix proj)/share/proj" >> "$GITHUB_ENV"
      - name: Set up R
        uses: TopoToolbox/actions/r-lib/actions/setup-r@main
        with:
          r-version: release
      - name: Install dependencies
        uses: TopoToolbox/actions/r-lib/actions/setup-r-dependencies@main
        with:
          extra-packages: any::rcmdcheck
      - name: Build and check
        uses: TopoToolbox/actions/r-lib/actions/check-r-package@main
